### ISSUE TITLE
[BUG] When having shuffel mode active, pressing the rewind button will also give random song

### ISSUE THREAD

**Issue by RotateRM** [Founntain/osuplayer#179]
**Describe the bug**
read title

**To Reproduce**
When having shuffel mode active, pressing the rewind button will also give random song

**Expected behavior**
jump back to last song listened to

**Additional context**
eh, no thanks

**Comment by Cesan** [comment]
depends on shuffle algorithm, please read instructions

**Comment by RotateRM** [comment]
where are these instructions ? also shouldn't that be the default then ?

**Comment by Founntain** [comment]
> where are these instructions ? also shouldn't that be the default then ?

On the i Button next where you select the shuffle algo ( in the settings )
