### ISSUE TITLE
[BUG]Linux segmentation fault.

### ISSUE THREAD

**Issue by Amic72** [Founntain/osuplayer#199]
**I am playing osu!lazer on Linux,using the X11 server.**
`
OS: Debian GNU/Linux 12 (bookworm) x86_64 
`
I can't get OsuPlayer to work on my system.

If I import the "client.realm" file, the program will immediately exit.

The terminal is telling me that a segmentation fault occurred.
```
$ LANG=en_US.UTF-8 ./OsuPlayer
INIT: Default | True | Parameter
INIT: HD-Audio Generic: HDMI 0 | True | Parameter
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
INIT: HD-Audio Generic: E281UA | False | Parameter
INIT: HD-Audio Generic: HDMI 2 | True | Parameter
INIT: HD-Audio Generic: HDMI 3 | True | Parameter
INIT: HD-Audio Generic: ALCS1200A Analog | True | Parameter
INIT: Rate Converter Plugin Using Libav/FFmpeg Library | False | Parameter
INIT: Rate Converter Plugin Using Samplerate Library | False | Parameter
INIT: Rate Converter Plugin Using Speex Resampler | False | Parameter
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
INIT: JACK Audio Connection Kit | False | Parameter
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
INIT: Open Sound System | False | Parameter
INIT: PulseAudio Sound Server | True | Parameter
INIT: Plugin using Speex DSP (resample, agc, denoise, echo, dereverb) | False | Parameter
INIT: Plugin for channel upmix (4,6,8) | False | Parameter
INIT: Plugin for channel downmix (stereo) with a simple spacialization | False | Parameter
段错误
```

**It also doesn't generate any logs in the "log" folder within the installation directory.
When I delete the "data" folder and try to open it, it seems to run normally.**
```
$ rm -r data/
$ LANG=en_US.UTF-8 ./OsuPlayer
INIT: Default | True | Parameter
INIT: HD-Audio Generic: HDMI 0 | True | Parameter
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
INIT: HD-Audio Generic: E281UA | False | Parameter
INIT: HD-Audio Generic: HDMI 2 | True | Parameter
INIT: HD-Audio Generic: HDMI 3 | True | Parameter
INIT: HD-Audio Generic: ALCS1200A Analog | True | Parameter
INIT: Rate Converter Plugin Using Libav/FFmpeg Library | False | Parameter
INIT: Rate Converter Plugin Using Samplerate Library | False | Parameter
INIT: Rate Converter Plugin Using Speex Resampler | False | Parameter
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
INIT: JACK Audio Connection Kit | False | Parameter
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
INIT: Open Sound System | False | Parameter
INIT: PulseAudio Sound Server | True | Parameter
INIT: Plugin using Speex DSP (resample, agc, denoise, echo, dereverb) | False | Parameter
INIT: Plugin for channel upmix (4,6,8) | False | Parameter
INIT: Plugin for channel downmix (stereo) with a simple spacialization | False | Parameter

```

**When I import the file, the program immediately exits without providing any information or error message other than the segmentation fault reported by the terminal.**
`
段错误
`

**After deleting the "data" folder or reinstalling osuplayer, if I import song collections instead of importing song information, it leaves some logs. However, it still exits with a segmentation fault and won't run again afterwards.**
```
A shit, it looks like you did something that the osu!player did not like. If you think this is a bug, please report this crashlog to Founntain by using the buttons below! (Also please don't forget to state how you achieved the crash e. g. what did you do, click etc.)

UTC Time: Tuesday, May 23, 2023 3:27PM

Error stacktrace below:
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at OsuPlayer.IO.Importer.CollectionImporter.ImportCollectionsAsync(ISongSourceProvider sourceProvider) in /home/runner/work/osuplayer/osuplayer/OsuPlayer.IO/Importer/CollectionImporter.cs:line 18
   at OsuPlayer.Views.SettingsView.ImportCollectionsClick(Object sender, RoutedEventArgs routedEventArgs) in /home/runner/work/osuplayer/osuplayer/OsuPlayer/Views/SettingsView.axaml.cs:line 108
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at OsuPlayer.Program.Main(String[] args) in /home/runner/work/osuplayer/osuplayer/OsuPlayer/Program.cs:line 31
```
**Afterward, it will be unable to run due to the segmentation fault.**

*I'm not a programming expert, but I will do my best to provide any other relevant information I can. I'm here seeking help, and apart from opening osu!lazer, there is no way for me to listen to the songs within the game. The song playlist in lazer still remains problematic.*

**Comment by Founntain** [comment]
Hey there @Amic72 and thanks for reporting the problem.

> After deleting the "data" folder or reinstalling osuplayer, if I import song collections instead of importing song information, it leaves some logs. However, it still exits with a segmentation fault and won't run again afterwards.

The reason why it produces a log file here is because it runs into a Exception during runtime and can write an error log. 

I will discuss with @Cesan what we can do about it and will look into it.

If you have Discord, you could join the osu!player discord server so we could response faster and even could provide some dev-builds were we think it could be fixed.

You can join ![our discord server by clicking here](https://discord.gg/RJQSc5B)

**Comment by Founntain** [comment]
If possible could you tell us which lazer version you are using?

**Comment by Amic72** [comment]
@Founntain 
> You can join ![our discord server by clicking here](https://camo.githubusercontent.com/1260ae068f0f5c29fb15e4876d1ffedeb66ad046ac494959ce6ca663b317ae30/68747470733a2f2f646973636f72642e67672f524a5153633542)

This link seems to be invalid and only gave me "Non-Image content-type returned.



> If possible could you tell us which lazer version you are using?

2023.513-0

**Comment by Founntain** [comment]
> This link seems to be invalid and only gave me "Non-Image content-type returned.

seems like github fucked up the embeding: https://discord.gg/RJQSc5B

anyhow. we already fixed the issue and we will soon create a new release for that
