### ISSUE TITLE
[BUG] Background colors behaving weirdly, all options having hight transparency

### ISSUE THREAD

**Issue by Quiel245** [Founntain/osuplayer#251]
**Describe the bug**
every time i open the app the background is on a grey color that is extremely uncomfortable for me, and when i try to change it with the "window background color" option it turns uncomfortably transparent, independent of the color i choose, and on restarting the app it will always start on the previously mentioned gray coloring
also, the "Use song background image" isn't working too

**To Reproduce**
1. Open the app
2. Click on "Settings"
3. Scroll down to window background color
4. change it to any option
5. See the weird transparency

**Expected behavior**
I expected the app to open always with the currently selected background color, and to not have any transparency on options other than the "Transparent" one

**Screenshots**
https://github.com/Founntain/osuplayer/assets/99212613/3c475ffc-a317-46cb-a78a-44cfb2c257ee

**Desktop:**
 - OS: Linux (endeavourOS)
 - Kernel Version: 6.6.2-arch1-1

**Additional context**
I don't know if that gray color is just what "none" is supposed to look like, but still

This started after the [2023.1118.1](https://github.com/Founntain/osuplayer/releases/tag/2023.1118.1) update, and still persists after [2023.1122.0](https://github.com/Founntain/osuplayer/releases/tag/2023.1122.0)

**Comment by Founntain** [comment]
This indeed not intended and might be a bug from migrating to Avalonia 11. I'll take a look tomorrow

**Comment by Quiel245** [comment]
Nice to know! thank you very much

**Comment by Founntain** [comment]
Quick Update I found out what the issue as and it also connects that the backgrounds are not working.

As you can see in the fixed version you can set the background color freely
![](https://gud.founntain.dev/f/XltpQ541SU.png)

**Comment by Quiel245** [comment]
Oooh, awesome
Thank you again!

**Comment by Founntain** [comment]
I really would appreciate when the new release is out and check if backgrounds work properly. If so please create a new issue then as I can't import songs on my WSL instance.

**Comment by Quiel245** [comment]
Ookie dokie, As soon as it comes out and I'm able to i'll test it right away!

**Comment by Founntain** [comment]
> Ookie dokie, As soon as it comes out and I'm able to i'll test it right away!

Sounds great! The Pull Request #253 just waits for @Cesan review!

**Comment by Quiel245** [comment]
Yup @Founntain, it seems to be working fine now!  
Only thing i'm not sure is that The "none" and transparent options are basically the same, is that how it is expected to be?

Little video showing how things are working now: 

https://github.com/Founntain/osuplayer/assets/99212613/f5de078a-8110-40b3-b239-99fb6b3185dd

**Comment by Founntain** [comment]
> Yup @Founntain, it seems to be working fine now! Only thing i'm not sure is that The "none" and transparent options are basically the same, is that how it is expected to be?

Yes it is expected. As those other options will always fallback to SolidColor (None)
```CSharp
TransparencyLevelHint = new[]
{
    // First Value to Try (Win 11 only)    Third and last value to try
    WindowTransparencyLevel.Mica, 
    // Second Value to Try  (Win and Mac only)
    WindowTransparencyLevel.AcrylicBlur,     
    // Last Value (SolidColor)
    WindowTransparencyLevel.None
};
```

**Comment by Quiel245** [comment]
ah i see, then it's all nice!

**Comment by Founntain** [comment]
> ah i see, then it's all nice!

Basicly if you are on Windows you could select Acrylic if you dont like Mica etc. but if you Use Mica and cant select it it will use None for Linux

**Comment by Quiel245** [comment]
hmm, thanks for the explanation, i think i got it better now!
