### ISSUE TITLE
[REQUEST] Adjust volume with scroll wheel

### ISSUE THREAD

**Issue by InitialDet** [Founntain/osuplayer#270]
Currently, we need to click the app to adjust the volume. It would be nice to quickly adjust the volume with the mouse scroll by hovering over the volume icon, similar to YouTube Music, with 1% increments if possible.

This is useful because you don't need to focus/tab out of the current window to adjust the volume (some applications minimize/pause themselves when they lose focus).

**Comment by Founntain** [comment]
We have to see if this is possible when the focus is currently not on the players main window. (I don't know if the events for that trigger properly when its not in focus)

I'll will test a bit around with it tomorrow
