### ISSUE TITLE
[REQUEST] Metadata in original language

### ISSUE THREAD

**Issue by Anti-Apple4life** [Founntain/osuplayer#274]
**Is your feature request related to a problem? Please describe.**
I have my metadata set to original data in osu!, and I cannot recognize the titles of certain songs without it.
**Describe the solution you'd like**
I would like osuplayer to be able to have a toggle that, when enabled, will pull metadata, such as titles and artists, from the original language

**Additional context**

Here are some screenshots in Lazer of what I am talking about
With original language toggle:
![image](https://github.com/Founntain/osuplayer/assets/59315931/8d02f56f-eef0-4335-8df9-4258963dc55b)
Without original language toggle
![image](https://github.com/Founntain/osuplayer/assets/59315931/67863424-aa0f-41ad-9033-43fd74cb63af)

**Comment by Founntain** [comment]
Well it we supported it once, but after a huge refactor and changes in the code base we forgot to re-add the setting in the settings.
Anyhow I re-implemented it and should be available after the PR is reviewed and merged as an update. You can find the setting in the visual settings then!
![image](https://github.com/Founntain/osuplayer/assets/28785685/30157397-0bae-497f-948a-27795cc555cc)

Screenshots:
![image](https://github.com/Founntain/osuplayer/assets/28785685/01fd2e13-4a93-480f-9e9d-d6a10266a912)
![image](https://github.com/Founntain/osuplayer/assets/28785685/5bb69d6e-3f17-4f12-8e19-f6308d40fe14)
![image](https://github.com/Founntain/osuplayer/assets/28785685/da6ee1b2-9b9e-48c2-8b69-7a5ba4950211)
