### ISSUE TITLE
[BUG] display titles and artists in unicode does not work

### ISSUE THREAD

**Issue by nanakura** [Founntain/osuplayer#281]
**Describe the bug**
display titles and articles in unicode does not work

**To Reproduce**
1. Set the “display titles and articles in unicode” switch to Yes
2. restart osuplayer

**Expected behavior**
titles displays in unicode

**Screenshots**
When osuplayer is restarted, the switch is reset
![QQ_1721625100034](https://github.com/user-attachments/assets/2e554061-3478-49fc-8c82-d451ea1da3b9)
**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Additional context**

**Comment by Founntain** [comment]
Will be fixed with #282 just needs review from @Cesan
