### ISSUE TITLE
[REQUEST] Songs are sorted by time added

### ISSUE THREAD

**Issue by nanakura** [Founntain/osuplayer#284]
**Is your feature request related to a problem? Please describe.**
Songs are sorted by time added

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/a3114220-79c8-48a0-ab5f-cf7e6b629039)
add a new mode here

**Comment by Founntain** [comment]
I sadly have to disappoint you with this, but the osu!.db **[according to the wiki](https://github.com/ppy/osu/wiki/Legacy-database-file-structure#beatmap-information)** does not provide this information to us, so we can't implement it.
Lazer has a `DateAdded` property for whole Beatmap Sets, but this pretty scuffed to use IMO, as the Date is mostly the same day for me as I imported all my songs from stable.
