### ISSUE TITLE
Create playlists from the collection.db

### ISSUE THREAD

**Issue by Founntain** [Founntain/osuplayer#38]

**Comment by ritikBhandari** [comment]
Hi,
Can I take up this issue if possible?

**Comment by Founntain** [comment]
> Hi, Can I take up this issue if possible?

We are currently in Setup phase with this project. Which means, that the issues that I just create are more of an To-Do list.
In principle I would say yes, but I would take this issue on to myself because there is more a lot To-Do what the title says.

Also we are looking for contributors that have experience with osu! and its internal structures itself (which I don't know if you have it looking at your GitHub activity), if you have this sure. If not I wouldn't recommend this issue or this repository at all.

**Comment by Founntain** [comment]
> Thanks for the info. Yes you are right I'm not quite familiar with osuplayer repo.

Don't worry.
I hope you find another repository, where you skills are needed and help others to build amazing software. 👍
Anyway thanks for the interested in the first place!
