### ISSUE TITLE
Implement blacklist

### ISSUE THREAD

**Issue by Founntain** [Founntain/osuplayer#56]
The blacklist needs to be implemented.

**Comment by Founntain** [comment]
@Cesan I assigned this issue to you, because I think this will suit you better. Because I think you like to work more with the internal structure of songs, playlists etc.
So if you want to tackle this issue let me know.

**Comment by Cesan** [comment]
Requires #67 because of the new hash system, which will also be used for this.

**Comment by Founntain** [comment]
#67 is merged
