### ISSUE TITLE
[BUG] Beatmaps with a high amount of Difs result in a lot of duplicates

### ISSUE THREAD

**Issue by Founntain** [Founntain/osuplayer#62]
We should reconsider if we should try to distinct audio files, to remove duplicate audio files, resulting in huge duplicates when scrolling throught the song list.

Those are all from the same set.
![](https://7.founntain.dev/81hDCHEE.png)

**Comment by Cesan** [comment]
This should not even be possible, because currently maps from the same beatmap set id are hard coded to import only one map for the map id.
