### ISSUE TITLE
[BUG] Adding a song to favorites results in adding a lot of songs

### ISSUE THREAD

**Issue by Founntain** [Founntain/osuplayer#63]
Title, see video

[*if video isn't displayed*](https://7.founntain.dev/Bk4nW1bn.mp4)
![](https://7.founntain.dev/Bk4nW1bn.mp4)

**Comment by Founntain** [comment]
I also realised that they are not saved in the playlist file.

I think this has something todo that the set is `-1`?
Full Json:

```JSON
{
  "LastSelectedPlaylist": "f2787497-2b42-477c-b3cd-d7d807aa4485",
  "Playlists": [
    {
      "Id": "f2787497-2b42-477c-b3cd-d7d807aa4485",
      "Name": "Favorites",
      "CreationTime": "2022-04-20T08:22:19.1949566Z",
      "Songs": [-1]
    }
  ]
}
```

**Comment by Cesan** [comment]
Yes, I will just redo the data structure to save the song name/artist as well to avoid this issue

**Comment by Founntain** [comment]
Maybe we should consider generating a hash from the full audio path.
It will always be unique and if use the same method the whole time it will be the same hash as always.

We would benifit from two things:
- We don't have to store the Artist / Name (which could result in duplication for sure)
- We solve the issue with different hashes between the *osu!.db* and *client.realm*

**Comment by Cesan** [comment]
Still, the path to the audio file located on stable osu! is different than the one in lazer, so this doesn't work

**Comment by Founntain** [comment]
> Still, the path to the audio file located on stable osu! is different than the one in lazer, so this doesn't work

Yes exactly. However you as a user you should consider using either the **db** or the **realm**

So they should be always unique, or does lazer changes his structure all the time?

**Comment by Cesan** [comment]
Then we could just use the hash found in the map entry, as this would result in the same

**Comment by Founntain** [comment]
Yes exactly. I like that you think about trying to find a solution to make both sides happy at the same time. It makes sense, but I don't see a good solution for this for now. It will mostly likely look ugly and shity (codewise).
The user has the ability to switch between databases at all times, however the user *should* stick to one. If they decided to hop between databases the whole time. Then in my opinion it's their own fault.

So we have two solutions I find practicable.

1. Use the hashes of the corresponding database *(easy solution)*
2. We use two playlists files (playlist_stable.json & playlist_lazer.json) one for its corresponding database. So hopping will be easier but you have playlists for each databse. *(more work solution)*

**Comment by Cesan** [comment]
Nevermind, I just found a way better solution. We can just use the old MD5 hash on lazer maps when importing from realm as it's always the first diff in the mapset that we use the hash from the osu!.db from, so this should be the same all the time

**Comment by Founntain** [comment]
> 

Sounds good to me, if user report instances where it is not the case and we can reproduce that then it is choose one db or stop crying :)
