### ISSUE TITLE
[BUG] CONSOLE OPENS ON STARTUP

### ISSUE THREAD

**Issue by RotateRM** [Founntain/osuplayer#81]
HOW TO FIND THE BUG : START THE CURRENT VERSION OF PLAYER OSU!

CONSOLE SHOW YOU AUDIO DEVICES AND WHEN NEXT SONG IS PLAYED IT SHOW TRUE OK!

PLEASE FIX!

**Comment by Founntain** [comment]
Why do you have to write it like this. I hate you for that and still I laughed with you on this on VC
![](https://c.tenor.com/0LqfAJneQKUAAAAM/why-why-why.gif)
