### ISSUE TITLE
Crashing when clicking next song or last song when repeat (not repeat 1 song) and shuffle are on

### ISSUE THREAD

**Issue by sajidbhuiya** [Founntain/osuplayer#89]
**Describe the bug**
The application will crash if you have repeat on (not repeat 1 song) and shuffle on, and then click next song or last song.

**To Reproduce**
1. Turn repeat on to repeat playlist 
2. Turn shuffle on
3.  Click on next song or last song
4.  Crash will occur

**Expected behavior**
It will go back to last song played or skip to next song in playlist.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 22621.160

**Comment by Founntain** [comment]
Adding the Crashlogs that were posted on discord!
@sajidbhuiya please include them next time here as well!

[20220623_190227.txt](https://github.com/Founntain/osuplayer/files/8970281/20220623_190227.txt)
[20220623_190709.txt](https://github.com/Founntain/osuplayer/files/8970282/20220623_190709.txt)

**Comment by Founntain** [comment]
@Cesan I would love if you would look into this issue, because you implemented most of the Repeat / Repeat-1 Logic and Shuffle.

**Comment by sajidbhuiya** [comment]
@Founntain ah my bad, forgot to include the files

**Comment by Cesan** [comment]
Will do asap
