### ISSUE TITLE
[BUG] Application crashes when changing menu immediately after click save on profile settings

### ISSUE THREAD

**Issue by sajidbhuiya** [Founntain/osuplayer#90]
**Describe the bug**
If you were to save your account profile settings and immediately go to a different menu of the application before waiting for the menu that you profile edits have saved, the application will crash.

**To Reproduce**
1. Go to edit your account profile
2. Save your profile settings
3.  Before the menu that your profile edits have saved, go to a different menu of the program (any menu works as far as I can tell)
4. Crash will occur

**Expected behavior**
Either it will enter the menu and still save the settings or lock me out from entering any menu before it saves.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 22621.160

**Additional context**
Video and crash log of the problem will be listed.

[Video](https://user-images.githubusercontent.com/95731834/175396408-b4c5d261-08fa-439b-b3c3-d7bdc23775a1.mp4)

[Crash Log](https://github.com/Founntain/osuplayer/files/8970835/20220623_204511.txt)

**Comment by Founntain** [comment]
@sajidbhuiya I made a Pull Request for this and created an release based on the branch of it.

Can you check if the release resolved the issue for you? Because I can't reproduce it because my internet connection is too fast!

https://github.com/Founntain/osuplayer/releases/tag/2022.624.0

**Comment by Founntain** [comment]
Thanks to @Cesan I changed something that should have been there already in the the release.

I made a new release from the issue-90 branch that can be found ![here](https://github.com/Founntain/osuplayer/releases/tag/2022.624.1)
